apiVersion: apps/v1
kind: Deployment
metadata:
  name: lake-liming
  labels:
    app: lake-liming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lake-liming
  template:
    metadata:
      labels:
        app: lake-liming
    spec:
      serviceAccountName: shiny-apps
      containers:
      - name: lake-liming
        image: europe-west1-docker.pkg.dev/niva-cd/images/lake-liming:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
          - name: http
            containerPort: 8501
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5

---
# Service exposing the timescale DB
apiVersion: v1
kind: Service
metadata:
  name: lake-liming
spec:
  ports:
  - name: http
    targetPort: http
    port: 80
    protocol: TCP
  selector:
    app: lake-liming
